# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# coding: utf-8
Area.create(:prefecture => '北海道')
Area.create(:prefecture => '青森県')
Area.create(:prefecture => '岩手県')
Area.create(:prefecture => '宮城県')
Area.create(:prefecture => '秋田県')
Area.create(:prefecture => '山形県')
Area.create(:prefecture => '福島県')
Area.create(:prefecture => '茨城県')
Area.create(:prefecture => '栃木県')
Area.create(:prefecture => '群馬県')
Area.create(:prefecture => '埼玉県')
Area.create(:prefecture => '千葉県')
Area.create(:prefecture => '東京都')
Area.create(:prefecture => '神奈川県')
Area.create(:prefecture => '新潟県')
Area.create(:prefecture => '富山県')
Area.create(:prefecture => '石川県')
Area.create(:prefecture => '福井県')
Area.create(:prefecture => '山梨県')
Area.create(:prefecture => '長野県')
Area.create(:prefecture => '岐阜県')
Area.create(:prefecture => '福岡県')
Area.create(:prefecture => '愛知県')
Area.create(:prefecture => '三重県')
Area.create(:prefecture => '滋賀県')
Area.create(:prefecture => '京都府')
Area.create(:prefecture => '大阪府')
Area.create(:prefecture => '兵庫県')
Area.create(:prefecture => '奈良県')
Area.create(:prefecture => '和歌山県')
Area.create(:prefecture => '鳥取県')
Area.create(:prefecture => '島根県')
Area.create(:prefecture => '岡山県')
Area.create(:prefecture => '広島県')
Area.create(:prefecture => '山口県')
Area.create(:prefecture => '徳島県')
Area.create(:prefecture => '香川県')
Area.create(:prefecture => '愛媛県')
Area.create(:prefecture => '高知県')
Area.create(:prefecture => '福岡県')
Area.create(:prefecture => '佐賀県')
Area.create(:prefecture => '長崎県')
Area.create(:prefecture => '熊本県')
Area.create(:prefecture => '大分県')
Area.create(:prefecture => '宮崎県')
Area.create(:prefecture => '鹿児島県')
Area.create(:prefecture => '沖縄県')
